FROM node:23

RUN npm i -g nodemon 
RUN mkdir -p /home/app

WORKDIR /home/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

EXPOSE 3000

# Configuración de nodemon para observar cambios
CMD ["nodemon", "--legacy-watch", "--watch", ".", "server.js"]
